version: '3'

volumes:
  jenkins_home:
  warfolder:
  

services:
  jenkins:
    image: jenkins/jenkins
    ports: 
      - "8081:8080"
      - "50000:50000" 
    volumes:
      - warfolder:/warfolder
      - jenkins_home:/var/jenkins_home
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
  wildfly:
    image: jboss/wildfly
    ports:
      - "8080:8080"
    volumes:
      - warfolder:/opt/jboss/wildfly/standalone/deployments
   
      